name: flutterkit
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  path: ^1.8.0
  args: ^2.5.0
  mason_logger: ^0.3.1
  mustache_template: ^2.0.0
  yaml: ^3.1.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

executables:
  flutterkit:
